"""add deleted_at

Revision ID: 0c8e05ea1c6a
Revises: d23c8847df71
Create Date: 2025-07-08 18:13:44.153625

"""
from typing import Sequence, Union
import sqlmodel.sql.sqltypes
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '0c8e05ea1c6a'
down_revision: Union[str, Sequence[str], None] = 'd23c8847df71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accountuser', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accountuser', 'deleted_at')
    # ### end Alembic commands ###
