"""fix error

Revision ID: 32d3e5f33259
Revises: 738429f2805b
Create Date: 2025-06-26 19:38:51.289798

"""
from typing import Sequence, Union
import sqlmodel.sql.sqltypes
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '32d3e5f33259'
down_revision: Union[str, Sequence[str], None] = '738429f2805b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accountuser', sa.Column('image_user', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accountuser', 'image_user')
    # ### end Alembic commands ###
