"""update

Revision ID: 373a35c278ec
Revises: 32d3e5f33259
Create Date: 2025-06-27 20:16:13.569474

"""
from typing import Sequence, Union
import sqlmodel.sql.sqltypes
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '373a35c278ec'
down_revision: Union[str, Sequence[str], None] = '32d3e5f33259'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accountuser', sa.Column('user_image', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_column('accountuser', 'image_user')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accountuser', sa.Column('image_user', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('accountuser', 'user_image')
    # ### end Alembic commands ###
