"""change

Revision ID: 60a93ecb8cf9
Revises: a345c6df5ecb
Create Date: 2025-07-04 15:02:15.404375

"""
from typing import Sequence, Union
import sqlmodel.sql.sqltypes
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '60a93ecb8cf9'
down_revision: Union[str, Sequence[str], None] = 'a345c6df5ecb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usermovievote', sa.Column('is_favorite', sa.Boolean(), nullable=True))
    op.add_column('usermovievote', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.drop_column('usermovievote', 'vote_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usermovievote', sa.Column('vote_type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('usermovievote', 'updated_at')
    op.drop_column('usermovievote', 'is_favorite')
    # ### end Alembic commands ###
