"""remove null field

Revision ID: 6a865919a578
Revises: ad07433c2310
Create Date: 2025-07-04 22:14:02.031966

"""

from typing import Sequence, Union
import sqlmodel.sql.sqltypes
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6a865919a578"
down_revision: Union[str, Sequence[str], None] = "ad07433c2310"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "UPDATE accountuser SET subscription = 'free' WHERE subscription IS NULL"
    )
    op.execute("UPDATE movie SET is_premium = false WHERE is_premium IS NULL")
    op.execute("UPDATE movie SET is_vip_only = false WHERE is_vip_only IS NULL")
    op.alter_column("accountuser", "subscription", nullable=False)
    op.alter_column("movie", "is_premium", nullable=False)
    op.alter_column("movie", "is_vip_only", nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("movie", "is_vip_only", nullable=True)
    op.alter_column("movie", "is_premium", nullable=True)
    op.alter_column("accountuser", "subscription", nullable=True)

    # ### end Alembic commands ###
