"""fix

Revision ID: a0f5100f8070
Revises: 60a93ecb8cf9
Create Date: 2025-07-04 16:43:40.497356

"""
from typing import Sequence, Union
import sqlmodel.sql.sqltypes
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = 'a0f5100f8070'
down_revision: Union[str, Sequence[str], None] = '60a93ecb8cf9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movie', sa.Column('rating', sa.Integer(), nullable=True))
    op.add_column('usermovievote', sa.Column('user_rating', sa.Integer(), nullable=True))
    op.alter_column('usermovievote', 'is_favorite',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_column('usermovievote', 'rating')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usermovievote', sa.Column('rating', sa.INTEGER(), autoincrement=False, nullable=True))
    op.alter_column('usermovievote', 'is_favorite',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_column('usermovievote', 'user_rating')
    op.drop_column('movie', 'rating')
    # ### end Alembic commands ###
