"""fix

Revision ID: a345c6df5ecb
Revises: 373a35c278ec
Create Date: 2025-07-02 17:29:39.556382

"""
from typing import Sequence, Union
import sqlmodel.sql.sqltypes
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = 'a345c6df5ecb'
down_revision: Union[str, Sequence[str], None] = '373a35c278ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movie', sa.Column('general_rating', sa.Integer(), nullable=True))
    op.add_column('usermovievote', sa.Column('rating', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usermovievote', 'rating')
    op.drop_column('movie', 'general_rating')
    # ### end Alembic commands ###
