"""add premium content

Revision ID: a852c1f3ddf6
Revises: 4134b675518c
Create Date: 2025-07-04 21:02:03.527484

"""

from typing import Sequence, Union
import sqlmodel.sql.sqltypes
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a852c1f3ddf6"
down_revision: Union[str, Sequence[str], None] = "4134b675518c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    subscription_enum = sa.Enum("free", "premium", "vip", name="subscriptiontype")
    subscription_enum.create(op.get_bind(), checkfirst=True)

    op.add_column(
        "accountuser", sa.Column("subscription", subscription_enum, nullable=True)
    )
    op.add_column("movie", sa.Column("is_premium", sa.Boolean(), nullable=True))
    op.add_column("movie", sa.Column("is_vip_only", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("movie", "is_vip_only")
    op.drop_column("movie", "is_premium")
    op.drop_column("accountuser", "subscription")

    sa.Enum(name="subscriptiontype").drop(op.get_bind(), checkfirst=True)

    # ### end Alembic commands ###
