"""modify column

Revision ID: bc28ea1c5b37
Revises: 61b956ec8284
Create Date: 2025-06-26 02:56:07.650863

"""
from typing import Sequence, Union
import sqlmodel.sql.sqltypes
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = 'bc28ea1c5b37'
down_revision: Union[str, Sequence[str], None] = '61b956ec8284'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movie', sa.Column('download_url', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True))
    op.add_column('movie', sa.Column('age_rating', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True))
    op.add_column('movie', sa.Column('duration', sa.Integer(), nullable=True))
    op.add_column('movie', sa.Column('trailer_url', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movie', 'trailer_url')
    op.drop_column('movie', 'duration')
    op.drop_column('movie', 'age_rating')
    op.drop_column('movie', 'download_url')
    # ### end Alembic commands ###
