"""added columns

Revision ID: f5fde563843f
Revises: 87920d5ce863
Create Date: 2025-06-21 14:40:00.023952

"""
from typing import Sequence, Union
import sqlmodel.sql.sqltypes
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5fde563843f'
down_revision: Union[str, Sequence[str], None] = '87920d5ce863'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('moviegenrelink',
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['genre_id'], ['genre.id'], ),
    sa.ForeignKeyConstraint(['movie_id'], ['movie.id'], ),
    sa.PrimaryKeyConstraint('movie_id', 'genre_id')
    )
    op.add_column('movie', sa.Column('id_tmdb', sa.Integer(), nullable=True))
    op.add_column('movie', sa.Column('popularity', sa.Float(), nullable=True))
    op.add_column('movie', sa.Column('adult', sa.Boolean(), nullable=False))
    op.add_column('movie', sa.Column('backdrop', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.add_column('movie', sa.Column('release_date', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True))
    op.add_column('movie', sa.Column('vote_average', sa.Float(), nullable=True))
    op.add_column('movie', sa.Column('vote_count', sa.Integer(), nullable=True))
    op.drop_index(op.f('ix_movie_rating'), table_name='movie')
    op.drop_index(op.f('ix_movie_release_year'), table_name='movie')
    op.create_index(op.f('ix_movie_category_id'), 'movie', ['category_id'], unique=False)
    op.create_index(op.f('ix_movie_id_tmdb'), 'movie', ['id_tmdb'], unique=True)
    op.create_index(op.f('ix_movie_popularity'), 'movie', ['popularity'], unique=False)
    op.create_index(op.f('ix_movie_release_date'), 'movie', ['release_date'], unique=False)
    op.create_index(op.f('ix_movie_vote_average'), 'movie', ['vote_average'], unique=False)
    op.create_index(op.f('ix_movie_vote_count'), 'movie', ['vote_count'], unique=False)
    op.drop_constraint(op.f('movie_genre_id_fkey'), 'movie', type_='foreignkey')
    op.drop_column('movie', 'genre_id')
    op.drop_column('movie', 'rating')
    op.drop_column('movie', 'release_year')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movie', sa.Column('release_year', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('movie', sa.Column('rating', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('movie', sa.Column('genre_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('movie_genre_id_fkey'), 'movie', 'genre', ['genre_id'], ['id'])
    op.drop_index(op.f('ix_movie_vote_count'), table_name='movie')
    op.drop_index(op.f('ix_movie_vote_average'), table_name='movie')
    op.drop_index(op.f('ix_movie_release_date'), table_name='movie')
    op.drop_index(op.f('ix_movie_popularity'), table_name='movie')
    op.drop_index(op.f('ix_movie_id_tmdb'), table_name='movie')
    op.drop_index(op.f('ix_movie_category_id'), table_name='movie')
    op.create_index(op.f('ix_movie_release_year'), 'movie', ['release_year'], unique=False)
    op.create_index(op.f('ix_movie_rating'), 'movie', ['rating'], unique=False)
    op.drop_column('movie', 'vote_count')
    op.drop_column('movie', 'vote_average')
    op.drop_column('movie', 'release_date')
    op.drop_column('movie', 'backdrop')
    op.drop_column('movie', 'adult')
    op.drop_column('movie', 'popularity')
    op.drop_column('movie', 'id_tmdb')
    op.drop_table('moviegenrelink')
    # ### end Alembic commands ###
